#!/usr/bin/env bash
# Summary: Show the current Any version and its origin
#
# Shows the currently selected Any version and how it was
# selected. To obtain only the version string, use `anyenv
# version-name'.

set -e
[ -n "$ANYENV_DEBUG" ] && set -x

for env in $(anyenv-envs); do
  if [ "$env" = "tfenv" ]; then
    echo "$env: $($env version-name)"
  else
    echo "$env: $($env version)"
  fi
done
