#!/usr/bin/env bash
#
# Summary: Uninstall a specific **anv
#
# Usage: anyenv uninstall [-f|--force] <**env>
#
#    -f  Attempt to remove the specified **env without prompting
#        for confirmation. If the **env does not exist, do not
#        display an error message.
#
# See `anyenv envs` for a complete list of installed envs.
#
set -e

# Provide anyenv completions
if [ "$1" = "--complete" ]; then
  echo --force
  exec anyenv envs --bare
fi

usage() {
  anyenv-help uninstall 2>/dev/null
  [ -z "$1" ] || exit "$1"
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  usage 0
fi

unset FORCE
if [ "$1" = "-f" ] || [ "$1" = "--force" ]; then
  FORCE=true
  shift
fi

[ "$#" -eq 1 ] || usage 1 >&2

DEFINITION="$1"
case "$DEFINITION" in
"" | -* )
  usage 1 >&2
  ;;
esac

#declare -a before_hooks after_hooks

#before_uninstall() {
#  local hook="$1"
#  before_hooks["${#before_hooks[@]}"]="$hook"
#}

#after_uninstall() {
#  local hook="$1"
#  after_hooks["${#after_hooks[@]}"]="$hook"
#}

#OLDIFS="$IFS"
#IFS=$'\n' scripts=(`anyenv-hooks uninstall`)
#IFS="$OLDIFS"
#for script in "${scripts[@]}"; do source "$script"; done


ENV_NAME="${DEFINITION##*/}"
PREFIX="${ANYENV_ROOT}/envs/${ENV_NAME}"

if [ -z "$FORCE" ]; then
  if [ ! -d "$PREFIX" ]; then
    echo "anyenv: env \`$ENV_NAME' not installed" >&2
    exit 1
  fi

  read -p "anyenv: remove $PREFIX? "
  case "$REPLY" in
  y* | Y* ) ;;
  * ) exit 1 ;;
  esac
fi

#for hook in "${before_hooks[@]}"; do eval "$hook"; done

if [ -d "$PREFIX" ]; then
  rm -rf "$PREFIX"
fi

#for hook in "${after_hooks[@]}"; do eval "$hook"; done
