#!/usr/bin/env bash
# Summary: List all **envs available to anyenv
# Usage: anyenv envs
#
# Lists all **env versions found in `$ANYENV_ROOT/envs/*'.

set -e
[ -n "$ANYENV_DEBUG" ] && set -x

for path in "${ANYENV_ROOT}/envs/"*; do
  if [ -d "$path" ]; then
    echo "${path##*/}"
  fi
done
